default_context:
  project_name: 'pythonlab'
  project_slug: 'pythonlab'
  domain_main: 'pythonlab.com'
  domain_staging: 'stag.pythonlab.com'
  docker_swarm_stack_name_main: 'pythonlab-com'
  docker_swarm_stack_name_staging: 'stag-pythonlab-com'
  secret_key: '1c8e4a84c13b774147fe172c402060d69454281b6c945ad9359f94ca7bfac3b2'
  first_superuser: 'admin@pythonlab.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.pythonlab.com", "https://stag.pythonlab.com", "https://pythonlab.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@pythonlab.com'
  postgres_password: '111111'
  pgadmin_default_user: 'admin@pythonlab.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'pythonlab.com'
  traefik_constraint_tag_staging: 'stag.pythonlab.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
